spring.application.name=Tnilam_Chatbot



# PostgreSQL DB
#spring.datasource.url=jdbc:postgresql://localhost:5432/mylocaldb
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.show-sql=false
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logging
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql=INFO

#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#server.port=9090




#MY SQL \\\

# Existing properties
server.port=8080
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/foodfactory
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

# Additional logging configurations
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.data.jpa=DEBUG





 

